/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_certificates"];
        put?: never;
        post: operations["create_certificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/certificates/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_certificate"];
        put?: never;
        post?: never;
        delete: operations["delete_certificate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/certificates/${number}/download`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download_certificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/certificates/${string}/revoke`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 吊销端点的文档占位函数。 */
        post: operations["revoke_certificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credential-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_credential_types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_credentials"];
        put?: never;
        post: operations["create_credential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/credentials/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_credential"];
        put: operations["update_credential"];
        post?: never;
        delete: operations["delete_credential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/credentials/${number}/test`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_credential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_histories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/histories/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单条运行历史的文档占位函数。 */
        get: operations["get_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/histories/${number}/logs`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录端点的文档占位函数。 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 通知渠道测试的文档占位函数。 */
        post: operations["test_notifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pipelines"];
        put?: never;
        post: operations["create_pipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/pipelines/${number}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pipeline"];
        put: operations["update_pipeline"];
        post?: never;
        delete: operations["delete_pipeline"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/pipelines/${number}/histories`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pipeline_histories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/pipelines/${number}/run`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动触发流水线的文档占位函数。 */
        post: operations["run_pipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 调度列表的文档占位函数。 */
        get: operations["list_schedules"];
        put?: never;
        /** 新建调度的文档占位函数。 */
        post: operations["create_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/trigger-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 触发审计分页查询的文档占位函数。 */
        get: operations["list_trigger_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/api/tasks/${string}/schema`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康探针的文档占位函数。 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 统一错误响应的内层对象。 */
        ApiErrorBody: {
            /** @description 稳定的机器可读错误码。 */
            code: string;
            /** @description 校验错误对应的字段；非字段错误为 `None`。 */
            field?: string | null;
            /** @description 可直接展示给用户的人类可读消息。 */
            message: string;
        };
        /** @description 统一成功响应。 */
        ApiResponse_CertificateResponse: {
            /** @description 证书响应。 */
            data: {
                /**
                 * Format: int64
                 * @description ACME 账号凭据标识。
                 */
                acme_account_access_id?: number | null;
                /** @description 证书 PEM 相对路径。 */
                cert_pem_path: string;
                /**
                 * Format: date-time
                 * @description 创建时间。
                 */
                created_at: string;
                /** @description 规范化后的域名集合。 */
                domains: string[];
                /** @description SHA-256 指纹。 */
                fingerprint: string;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /** @description 签发者。 */
                issuer?: string | null;
                /** @description 私钥 PEM 相对路径。 */
                key_pem_path: string;
                /**
                 * Format: date-time
                 * @description 到期时间。
                 */
                not_after: string;
                /**
                 * Format: date-time
                 * @description 生效时间。
                 */
                not_before: string;
                /**
                 * Format: date-time
                 * @description 吊销时间。
                 */
                revoked_at?: string | null;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_ConnectivityResponse: {
            /** @description 凭据连通性测试响应。 */
            data: {
                /** @description 不可用时的脱敏原因。 */
                reason?: string | null;
                /** @description `ok`、`unavailable` 或 `not_testable`。 */
                status: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_CredentialDetailResponse: {
            /**
             * @description 凭据详情响应：额外带回**解密后的字段值**。
             *
             *     编辑表单必须能回填现值——PUT 是整体替换语义，拿不到旧值的编辑等于
             *     一保存就把密钥清空。端点仅管理员令牌可达，与「谁能改凭据」同权限；
             *     列表响应（`CredentialResponse`）依旧不带字段。
             */
            data: {
                /**
                 * Format: date-time
                 * @description 创建时间。
                 */
                created_at: string;
                /** @description 解密后的字段值（编辑回填用）。 */
                fields: unknown;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /** @description 展示名称。 */
                name: string;
                /** @description 凭据类型。 */
                type_id: string;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_CredentialResponse: {
            /** @description 凭据列表项响应。不返回加密字段。 */
            data: {
                /**
                 * Format: date-time
                 * @description 创建时间。
                 */
                created_at: string;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /** @description 展示名称。 */
                name: string;
                /** @description 凭据类型。 */
                type_id: string;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_HistoryResponse: {
            /** @description 运行历史响应。 */
            data: {
                /** @description 失败摘要。 */
                error_message?: string | null;
                /**
                 * Format: date-time
                 * @description 结束时间。
                 */
                finished_at?: string | null;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /**
                 * Format: int64
                 * @description 所属流水线。
                 */
                pipeline_id: number;
                /**
                 * Format: date-time
                 * @description 开始时间。
                 */
                started_at: string;
                /** @description 运行状态。 */
                status: string;
                /** @description 触发来源。 */
                trigger_source: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_LoginResponse: {
            /** @description 登录响应 DTO。 */
            data: {
                /**
                 * Format: int64
                 * @description 有效期（秒）。
                 */
                expires_in: number;
                /** @description 访问令牌。 */
                token: string;
                /** @description 令牌类型，固定 `Bearer`。 */
                token_type: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_NotificationTestResponse: {
            /** @description 通知渠道测试响应：逐渠道给出投递结果。 */
            data: {
                /** @description 每个被测渠道一条结果，顺序与配置一致。 */
                results: components["schemas"]["NotificationTestResult"][];
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_PageResponse_CertificateResponse: {
            /** @description 通用分页响应。 */
            data: {
                /** @description 当前页数据。 */
                items: {
                    /**
                     * Format: int64
                     * @description ACME 账号凭据标识。
                     */
                    acme_account_access_id?: number | null;
                    /** @description 证书 PEM 相对路径。 */
                    cert_pem_path: string;
                    /**
                     * Format: date-time
                     * @description 创建时间。
                     */
                    created_at: string;
                    /** @description 规范化后的域名集合。 */
                    domains: string[];
                    /** @description SHA-256 指纹。 */
                    fingerprint: string;
                    /**
                     * Format: int64
                     * @description 主键。
                     */
                    id: number;
                    /** @description 签发者。 */
                    issuer?: string | null;
                    /** @description 私钥 PEM 相对路径。 */
                    key_pem_path: string;
                    /**
                     * Format: date-time
                     * @description 到期时间。
                     */
                    not_after: string;
                    /**
                     * Format: date-time
                     * @description 生效时间。
                     */
                    not_before: string;
                    /**
                     * Format: date-time
                     * @description 吊销时间。
                     */
                    revoked_at?: string | null;
                    /**
                     * Format: date-time
                     * @description 更新时间。
                     */
                    updated_at: string;
                }[];
                /**
                 * Format: int64
                 * @description 当前页码。
                 */
                page: number;
                /**
                 * Format: int64
                 * @description 每页条数。
                 */
                page_size: number;
                /**
                 * Format: int64
                 * @description 符合条件的总条数。
                 */
                total: number;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_PageResponse_CredentialResponse: {
            /** @description 通用分页响应。 */
            data: {
                /** @description 当前页数据。 */
                items: {
                    /**
                     * Format: date-time
                     * @description 创建时间。
                     */
                    created_at: string;
                    /**
                     * Format: int64
                     * @description 主键。
                     */
                    id: number;
                    /** @description 展示名称。 */
                    name: string;
                    /** @description 凭据类型。 */
                    type_id: string;
                    /**
                     * Format: date-time
                     * @description 更新时间。
                     */
                    updated_at: string;
                }[];
                /**
                 * Format: int64
                 * @description 当前页码。
                 */
                page: number;
                /**
                 * Format: int64
                 * @description 每页条数。
                 */
                page_size: number;
                /**
                 * Format: int64
                 * @description 符合条件的总条数。
                 */
                total: number;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_PageResponse_HistoryResponse: {
            /** @description 通用分页响应。 */
            data: {
                /** @description 当前页数据。 */
                items: {
                    /** @description 失败摘要。 */
                    error_message?: string | null;
                    /**
                     * Format: date-time
                     * @description 结束时间。
                     */
                    finished_at?: string | null;
                    /**
                     * Format: int64
                     * @description 主键。
                     */
                    id: number;
                    /**
                     * Format: int64
                     * @description 所属流水线。
                     */
                    pipeline_id: number;
                    /**
                     * Format: date-time
                     * @description 开始时间。
                     */
                    started_at: string;
                    /** @description 运行状态。 */
                    status: string;
                    /** @description 触发来源。 */
                    trigger_source: string;
                }[];
                /**
                 * Format: int64
                 * @description 当前页码。
                 */
                page: number;
                /**
                 * Format: int64
                 * @description 每页条数。
                 */
                page_size: number;
                /**
                 * Format: int64
                 * @description 符合条件的总条数。
                 */
                total: number;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_PageResponse_PipelineSummaryResponse: {
            /** @description 通用分页响应。 */
            data: {
                /** @description 当前页数据。 */
                items: {
                    /** @description 可选描述。 */
                    description?: string | null;
                    /** @description 是否启用。 */
                    enabled: boolean;
                    /**
                     * Format: int64
                     * @description 主键。
                     */
                    id: number;
                    /** @description 展示名称。 */
                    name: string;
                    /** @description 步骤数量。 */
                    step_count: number;
                    /**
                     * Format: date-time
                     * @description 更新时间。
                     */
                    updated_at: string;
                }[];
                /**
                 * Format: int64
                 * @description 当前页码。
                 */
                page: number;
                /**
                 * Format: int64
                 * @description 每页条数。
                 */
                page_size: number;
                /**
                 * Format: int64
                 * @description 符合条件的总条数。
                 */
                total: number;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_PageResponse_TriggerLogResponse: {
            /** @description 通用分页响应。 */
            data: {
                /** @description 当前页数据。 */
                items: {
                    /** @description 触发说明（如命中的证书域名、失败原因）。 */
                    detail?: string | null;
                    /**
                     * Format: int64
                     * @description 主键。
                     */
                    id: number;
                    /**
                     * Format: int64
                     * @description 被触发的流水线。
                     */
                    pipeline_id: number;
                    /** @description 触发来源：`cron` / `renewal`。 */
                    source: string;
                    /**
                     * Format: date-time
                     * @description 触发时间。
                     */
                    triggered_at: string;
                }[];
                /**
                 * Format: int64
                 * @description 当前页码。
                 */
                page: number;
                /**
                 * Format: int64
                 * @description 每页条数。
                 */
                page_size: number;
                /**
                 * Format: int64
                 * @description 符合条件的总条数。
                 */
                total: number;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_PipelineResponse: {
            /** @description 完整流水线响应。 */
            data: {
                /**
                 * Format: date-time
                 * @description 创建时间。
                 */
                created_at: string;
                /** @description 可选描述。 */
                description?: string | null;
                /** @description 是否启用。 */
                enabled: boolean;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /** @description 展示名称。 */
                name: string;
                /** @description 有序步骤。 */
                steps: components["schemas"]["PipelineStepResponse"][];
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_RevokeResponse: {
            /** @description 吊销结果。 */
            data: {
                /**
                 * Format: int64
                 * @description 证书记录标识。
                 */
                cert_id: number;
                /**
                 * Format: date-time
                 * @description 本地记录的吊销时间。
                 */
                revoked_at: string;
                /** @description 是否本次调用完成了吊销（`false` 表示 CA 侧早已吊销，本次只是同步状态）。 */
                revoked_now: boolean;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_RunResponse: {
            /** @description 手动触发一次流水线运行的响应。 */
            data: {
                /**
                 * Format: int64
                 * @description 本次运行的运行历史主键。
                 */
                history_id: number;
                /** @description 运行状态；本接口立即返回，恒为 `running`。 */
                status: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_ScheduleResponse: {
            /** @description 调度配置响应。 */
            data: {
                /** @description 停机补跑策略。 */
                catch_up: boolean;
                /** @description cron 表达式原文。 */
                cron?: string | null;
                /** @description 是否启用。 */
                enabled: boolean;
                /**
                 * Format: date-time
                 * @description 上次触发时间。
                 */
                last_triggered_at?: string | null;
                /**
                 * Format: date-time
                 * @description 下次预计触发时间。
                 */
                next_trigger_at?: string | null;
                /**
                 * Format: int64
                 * @description 所属流水线。
                 */
                pipeline_id: number;
                /** @description 负责续期的域名集合。 */
                renewal_domains?: string[] | null;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            };
        };
        /** @description 统一成功响应。 */
        ApiResponse_Vec_HistoryLogResponse: {
            data: {
                /**
                 * Format: date-time
                 * @description 产生时间。
                 */
                created_at: string;
                /** @description 日志级别。 */
                level: string;
                /** @description 日志消息。 */
                message: string;
                /**
                 * Format: int32
                 * @description 步骤顺序。
                 */
                step_index: number;
            }[];
        };
        /** @description 统一成功响应。 */
        ApiResponse_Vec_ScheduleResponse: {
            data: {
                /** @description 停机补跑策略。 */
                catch_up: boolean;
                /** @description cron 表达式原文。 */
                cron?: string | null;
                /** @description 是否启用。 */
                enabled: boolean;
                /**
                 * Format: date-time
                 * @description 上次触发时间。
                 */
                last_triggered_at?: string | null;
                /**
                 * Format: date-time
                 * @description 下次预计触发时间。
                 */
                next_trigger_at?: string | null;
                /**
                 * Format: int64
                 * @description 所属流水线。
                 */
                pipeline_id: number;
                /** @description 负责续期的域名集合。 */
                renewal_domains?: string[] | null;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            }[];
        };
        /** @description 证书下载查询参数。 */
        CertificateDownloadQuery: {
            /** @description 目标格式：`pem`（默认）、`der`、`pfx`、`jks`、`p7b`。 */
            format?: string | null;
            /** @description PFX / JKS 的口令；未设置时使用约定默认值。 */
            password?: string | null;
        };
        /** @description 证书创建 DTO。 */
        CertificateRequest: {
            /**
             * Format: int64
             * @description ACME 账号凭据标识。
             */
            acme_account_access_id?: number | null;
            /** @description 证书 PEM 相对路径。 */
            cert_pem_path: string;
            /** @description 证书覆盖的域名集合。 */
            domains: string[];
            /** @description SHA-256 指纹。 */
            fingerprint: string;
            /** @description 签发者。 */
            issuer?: string | null;
            /** @description 私钥 PEM 相对路径。 */
            key_pem_path: string;
            /**
             * Format: date-time
             * @description 到期时间。
             */
            not_after: string;
            /**
             * Format: date-time
             * @description 生效时间。
             */
            not_before: string;
        };
        /** @description 证书响应。 */
        CertificateResponse: {
            /**
             * Format: int64
             * @description ACME 账号凭据标识。
             */
            acme_account_access_id?: number | null;
            /** @description 证书 PEM 相对路径。 */
            cert_pem_path: string;
            /**
             * Format: date-time
             * @description 创建时间。
             */
            created_at: string;
            /** @description 规范化后的域名集合。 */
            domains: string[];
            /** @description SHA-256 指纹。 */
            fingerprint: string;
            /**
             * Format: int64
             * @description 主键。
             */
            id: number;
            /** @description 签发者。 */
            issuer?: string | null;
            /** @description 私钥 PEM 相对路径。 */
            key_pem_path: string;
            /**
             * Format: date-time
             * @description 到期时间。
             */
            not_after: string;
            /**
             * Format: date-time
             * @description 生效时间。
             */
            not_before: string;
            /**
             * Format: date-time
             * @description 吊销时间。
             */
            revoked_at?: string | null;
            /**
             * Format: date-time
             * @description 更新时间。
             */
            updated_at: string;
        };
        /** @description 凭据连通性测试响应。 */
        ConnectivityResponse: {
            /** @description 不可用时的脱敏原因。 */
            reason?: string | null;
            /** @description `ok`、`unavailable` 或 `not_testable`。 */
            status: string;
        };
        /**
         * @description 凭据详情响应：额外带回**解密后的字段值**。
         *
         *     编辑表单必须能回填现值——PUT 是整体替换语义，拿不到旧值的编辑等于
         *     一保存就把密钥清空。端点仅管理员令牌可达，与「谁能改凭据」同权限；
         *     列表响应（`CredentialResponse`）依旧不带字段。
         */
        CredentialDetailResponse: {
            /**
             * Format: date-time
             * @description 创建时间。
             */
            created_at: string;
            /** @description 解密后的字段值（编辑回填用）。 */
            fields: unknown;
            /**
             * Format: int64
             * @description 主键。
             */
            id: number;
            /** @description 展示名称。 */
            name: string;
            /** @description 凭据类型。 */
            type_id: string;
            /**
             * Format: date-time
             * @description 更新时间。
             */
            updated_at: string;
        };
        /** @description 凭据创建/更新 DTO。 */
        CredentialRequest: {
            /** @description 未加密字段值；仅在进程内短暂存在。 */
            fields: unknown;
            /** @description 展示名称。 */
            name: string;
            /** @description 已注册的凭据类型。 */
            type_id: string;
        };
        /** @description 凭据列表项响应。不返回加密字段。 */
        CredentialResponse: {
            /**
             * Format: date-time
             * @description 创建时间。
             */
            created_at: string;
            /**
             * Format: int64
             * @description 主键。
             */
            id: number;
            /** @description 展示名称。 */
            name: string;
            /** @description 凭据类型。 */
            type_id: string;
            /**
             * Format: date-time
             * @description 更新时间。
             */
            updated_at: string;
        };
        /** @description 凭据类型响应。 */
        CredentialTypeResponse: {
            /** @description 展示名称。 */
            display_name: string;
            /** @description 字段 JSON Schema。 */
            schema: unknown;
            /** @description 类型标识。 */
            type_id: string;
        };
        /** @description 步骤日志响应。 */
        HistoryLogResponse: {
            /**
             * Format: date-time
             * @description 产生时间。
             */
            created_at: string;
            /** @description 日志级别。 */
            level: string;
            /** @description 日志消息。 */
            message: string;
            /**
             * Format: int32
             * @description 步骤顺序。
             */
            step_index: number;
        };
        /** @description 运行历史响应。 */
        HistoryResponse: {
            /** @description 失败摘要。 */
            error_message?: string | null;
            /**
             * Format: date-time
             * @description 结束时间。
             */
            finished_at?: string | null;
            /**
             * Format: int64
             * @description 主键。
             */
            id: number;
            /**
             * Format: int64
             * @description 所属流水线。
             */
            pipeline_id: number;
            /**
             * Format: date-time
             * @description 开始时间。
             */
            started_at: string;
            /** @description 运行状态。 */
            status: string;
            /** @description 触发来源。 */
            trigger_source: string;
        };
        /** @description 登录请求 DTO。 */
        LoginRequest: {
            /** @description 管理员口令。 */
            password: string;
            /** @description 管理员用户名。 */
            username: string;
        };
        /** @description 登录响应 DTO。 */
        LoginResponse: {
            /**
             * Format: int64
             * @description 有效期（秒）。
             */
            expires_in: number;
            /** @description 访问令牌。 */
            token: string;
            /** @description 令牌类型，固定 `Bearer`。 */
            token_type: string;
        };
        /** @description 通知渠道测试请求。 */
        NotificationTestRequest: {
            /** @description 要测试的渠道名；缺省时测试全部启用渠道。 */
            name?: string | null;
        };
        /** @description 通知渠道测试响应：逐渠道给出投递结果。 */
        NotificationTestResponse: {
            /** @description 每个被测渠道一条结果，顺序与配置一致。 */
            results: components["schemas"]["NotificationTestResult"][];
        };
        /** @description 单个通知渠道的测试投递结果。 */
        NotificationTestResult: {
            /** @description 失败原因。 */
            error?: string | null;
            /** @description 渠道名。 */
            name: string;
            /** @description 投递是否成功。 */
            ok: boolean;
            /** @description 适配器类型。 */
            provider: string;
        };
        /** @description 通用分页响应。 */
        PageResponse_CertificateResponse: {
            /** @description 当前页数据。 */
            items: {
                /**
                 * Format: int64
                 * @description ACME 账号凭据标识。
                 */
                acme_account_access_id?: number | null;
                /** @description 证书 PEM 相对路径。 */
                cert_pem_path: string;
                /**
                 * Format: date-time
                 * @description 创建时间。
                 */
                created_at: string;
                /** @description 规范化后的域名集合。 */
                domains: string[];
                /** @description SHA-256 指纹。 */
                fingerprint: string;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /** @description 签发者。 */
                issuer?: string | null;
                /** @description 私钥 PEM 相对路径。 */
                key_pem_path: string;
                /**
                 * Format: date-time
                 * @description 到期时间。
                 */
                not_after: string;
                /**
                 * Format: date-time
                 * @description 生效时间。
                 */
                not_before: string;
                /**
                 * Format: date-time
                 * @description 吊销时间。
                 */
                revoked_at?: string | null;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            }[];
            /**
             * Format: int64
             * @description 当前页码。
             */
            page: number;
            /**
             * Format: int64
             * @description 每页条数。
             */
            page_size: number;
            /**
             * Format: int64
             * @description 符合条件的总条数。
             */
            total: number;
        };
        /** @description 通用分页响应。 */
        PageResponse_CredentialResponse: {
            /** @description 当前页数据。 */
            items: {
                /**
                 * Format: date-time
                 * @description 创建时间。
                 */
                created_at: string;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /** @description 展示名称。 */
                name: string;
                /** @description 凭据类型。 */
                type_id: string;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            }[];
            /**
             * Format: int64
             * @description 当前页码。
             */
            page: number;
            /**
             * Format: int64
             * @description 每页条数。
             */
            page_size: number;
            /**
             * Format: int64
             * @description 符合条件的总条数。
             */
            total: number;
        };
        /** @description 通用分页响应。 */
        PageResponse_HistoryResponse: {
            /** @description 当前页数据。 */
            items: {
                /** @description 失败摘要。 */
                error_message?: string | null;
                /**
                 * Format: date-time
                 * @description 结束时间。
                 */
                finished_at?: string | null;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /**
                 * Format: int64
                 * @description 所属流水线。
                 */
                pipeline_id: number;
                /**
                 * Format: date-time
                 * @description 开始时间。
                 */
                started_at: string;
                /** @description 运行状态。 */
                status: string;
                /** @description 触发来源。 */
                trigger_source: string;
            }[];
            /**
             * Format: int64
             * @description 当前页码。
             */
            page: number;
            /**
             * Format: int64
             * @description 每页条数。
             */
            page_size: number;
            /**
             * Format: int64
             * @description 符合条件的总条数。
             */
            total: number;
        };
        /** @description 通用分页响应。 */
        PageResponse_PipelineSummaryResponse: {
            /** @description 当前页数据。 */
            items: {
                /** @description 可选描述。 */
                description?: string | null;
                /** @description 是否启用。 */
                enabled: boolean;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /** @description 展示名称。 */
                name: string;
                /** @description 步骤数量。 */
                step_count: number;
                /**
                 * Format: date-time
                 * @description 更新时间。
                 */
                updated_at: string;
            }[];
            /**
             * Format: int64
             * @description 当前页码。
             */
            page: number;
            /**
             * Format: int64
             * @description 每页条数。
             */
            page_size: number;
            /**
             * Format: int64
             * @description 符合条件的总条数。
             */
            total: number;
        };
        /** @description 通用分页响应。 */
        PageResponse_TriggerLogResponse: {
            /** @description 当前页数据。 */
            items: {
                /** @description 触发说明（如命中的证书域名、失败原因）。 */
                detail?: string | null;
                /**
                 * Format: int64
                 * @description 主键。
                 */
                id: number;
                /**
                 * Format: int64
                 * @description 被触发的流水线。
                 */
                pipeline_id: number;
                /** @description 触发来源：`cron` / `renewal`。 */
                source: string;
                /**
                 * Format: date-time
                 * @description 触发时间。
                 */
                triggered_at: string;
            }[];
            /**
             * Format: int64
             * @description 当前页码。
             */
            page: number;
            /**
             * Format: int64
             * @description 每页条数。
             */
            page_size: number;
            /**
             * Format: int64
             * @description 符合条件的总条数。
             */
            total: number;
        };
        /** @description 流水线创建/更新 DTO。 */
        PipelineRequest: {
            /** @description 可选描述。 */
            description?: string | null;
            /** @description 流水线级开关，默认启用。 */
            enabled?: boolean;
            /** @description 展示名称。 */
            name: string;
            /** @description 按执行顺序排列的步骤。 */
            steps: components["schemas"]["PipelineStepRequest"][];
        };
        /** @description 完整流水线响应。 */
        PipelineResponse: {
            /**
             * Format: date-time
             * @description 创建时间。
             */
            created_at: string;
            /** @description 可选描述。 */
            description?: string | null;
            /** @description 是否启用。 */
            enabled: boolean;
            /**
             * Format: int64
             * @description 主键。
             */
            id: number;
            /** @description 展示名称。 */
            name: string;
            /** @description 有序步骤。 */
            steps: components["schemas"]["PipelineStepResponse"][];
            /**
             * Format: date-time
             * @description 更新时间。
             */
            updated_at: string;
        };
        /** @description 流水线步骤输入 DTO。 */
        PipelineStepRequest: {
            /** @description 是否启用，默认启用。 */
            enabled?: boolean;
            /** @description 任务输入；未提供时使用空 JSON 对象。 */
            input?: unknown;
            /** @description 任务类型标识。 */
            type_id: string;
        };
        /** @description 流水线步骤响应。 */
        PipelineStepResponse: {
            /** @description 是否启用。 */
            enabled: boolean;
            /**
             * Format: int64
             * @description 步骤主键。
             */
            id: number;
            /** @description JSON 输入。 */
            input: unknown;
            /**
             * Format: int32
             * @description 执行顺序。
             */
            order_index: number;
            /** @description 任务类型标识。 */
            type_id: string;
        };
        /** @description 流水线概要响应。 */
        PipelineSummaryResponse: {
            /** @description 可选描述。 */
            description?: string | null;
            /** @description 是否启用。 */
            enabled: boolean;
            /**
             * Format: int64
             * @description 主键。
             */
            id: number;
            /** @description 展示名称。 */
            name: string;
            /** @description 步骤数量。 */
            step_count: number;
            /**
             * Format: date-time
             * @description 更新时间。
             */
            updated_at: string;
        };
        /** @description 吊销请求体：可选吊销原因（RFC 5280 的 RevocationReason）。 */
        RevokeRequest: {
            /**
             * Format: int32
             * @description 吊销原因代码（0..=10，RFC 5280）；缺省时由 CA 决定。
             */
            reason?: number | null;
        };
        /** @description 吊销结果。 */
        RevokeResponse: {
            /**
             * Format: int64
             * @description 证书记录标识。
             */
            cert_id: number;
            /**
             * Format: date-time
             * @description 本地记录的吊销时间。
             */
            revoked_at: string;
            /** @description 是否本次调用完成了吊销（`false` 表示 CA 侧早已吊销，本次只是同步状态）。 */
            revoked_now: boolean;
        };
        /** @description 手动触发一次流水线运行的响应。 */
        RunResponse: {
            /**
             * Format: int64
             * @description 本次运行的运行历史主键。
             */
            history_id: number;
            /** @description 运行状态；本接口立即返回，恒为 `running`。 */
            status: string;
        };
        /** @description 新建调度请求。 */
        ScheduleCreateRequest: {
            /** @description 停机补跑策略：追赶最近一次。 */
            catch_up?: boolean;
            /** @description cron 表达式（5 或 6 段）；`None`/空表示不按 cron 触发。 */
            cron?: string | null;
            /** @description 是否启用。 */
            enabled?: boolean;
            /**
             * Format: int64
             * @description 所属流水线。
             */
            pipeline_id: number;
            /** @description 负责续期的域名集合。 */
            renewal_domains?: string[] | null;
        };
        /** @description 调度配置响应。 */
        ScheduleResponse: {
            /** @description 停机补跑策略。 */
            catch_up: boolean;
            /** @description cron 表达式原文。 */
            cron?: string | null;
            /** @description 是否启用。 */
            enabled: boolean;
            /**
             * Format: date-time
             * @description 上次触发时间。
             */
            last_triggered_at?: string | null;
            /**
             * Format: date-time
             * @description 下次预计触发时间。
             */
            next_trigger_at?: string | null;
            /**
             * Format: int64
             * @description 所属流水线。
             */
            pipeline_id: number;
            /** @description 负责续期的域名集合。 */
            renewal_domains?: string[] | null;
            /**
             * Format: date-time
             * @description 更新时间。
             */
            updated_at: string;
        };
        /** @description 任务类型响应。 */
        TaskTypeResponse: {
            /** @description 展示名称；当前步骤 Trait 没有单独的展示名时使用类型标识。 */
            display_name: string;
            /** @description 输入 JSON Schema；未声明时为 `None`。 */
            schema?: unknown;
            /** @description 类型标识。 */
            type_id: string;
        };
        /** @description 触发记录查询参数。 */
        TriggerLogQueryParams: {
            /**
             * Format: int64
             * @description 页码。
             */
            page?: number | null;
            /**
             * Format: int64
             * @description 每页条数。
             */
            page_size?: number | null;
            /**
             * Format: int64
             * @description 按流水线过滤。
             */
            pipeline_id?: number | null;
        };
        /** @description 触发记录响应。 */
        TriggerLogResponse: {
            /** @description 触发说明（如命中的证书域名、失败原因）。 */
            detail?: string | null;
            /**
             * Format: int64
             * @description 主键。
             */
            id: number;
            /**
             * Format: int64
             * @description 被触发的流水线。
             */
            pipeline_id: number;
            /** @description 触发来源：`cron` / `renewal`。 */
            source: string;
            /**
             * Format: date-time
             * @description 触发时间。
             */
            triggered_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_certificates: {
        parameters: {
            query?: {
                /** @description 域名模糊过滤 */
                domain?: string;
                /** @description ascending / descending */
                sort?: string;
                /** @description 页码 */
                page?: number;
                /** @description 每页条数 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 证书分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResponse_CertificateResponse"];
                };
            };
        };
    };
    create_certificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CertificateResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    get_certificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 证书标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CertificateResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    delete_certificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 证书标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    download_certificate: {
        parameters: {
            query?: {
                /** @description pem / der / pfx / jks / p7b */
                format?: string;
                /** @description PFX / JKS 口令 */
                password?: string;
            };
            header?: never;
            path: {
                /** @description 证书标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 证书文件下载 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    revoke_certificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RevokeResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_credential_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 凭据类型与字段 Schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_credentials: {
        parameters: {
            query?: {
                /** @description 页码 */
                page?: number;
                /** @description 每页条数 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 凭据分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResponse_CredentialResponse"];
                };
            };
        };
    };
    create_credential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CredentialResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    get_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 凭据标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 凭据详情（含解密字段值，供编辑回填） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CredentialDetailResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    update_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 凭据标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CredentialResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    delete_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 凭据标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    test_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 凭据标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 连通性结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConnectivityResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_histories: {
        parameters: {
            query?: {
                /** @description 按流水线过滤 */
                pipeline_id?: number;
                /** @description 页码 */
                page?: number;
                /** @description 每页条数 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行历史分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResponse_HistoryResponse"];
                };
            };
        };
    };
    get_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 历史主键 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HistoryResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    history_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 历史主键 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 步骤日志 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_HistoryLogResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_LoginResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    test_notifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["NotificationTestRequest"];
            };
        };
        responses: {
            /** @description 逐渠道投递结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NotificationTestResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_pipelines: {
        parameters: {
            query?: {
                /** @description 页码 */
                page?: number;
                /** @description 每页条数 */
                page_size?: number;
                /** @description 名称模糊过滤 */
                name?: string;
                /** @description 启用状态过滤 */
                enabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 流水线分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResponse_PipelineSummaryResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    create_pipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PipelineResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    get_pipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 流水线标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PipelineResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    update_pipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 流水线标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PipelineResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    delete_pipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 流水线标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_pipeline_histories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 流水线标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 流水线运行历史分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_pipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 流水线标识 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已开始运行，返回运行历史标识 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RunResponse"];
                };
            };
            /** @description 流水线已停用 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description 流水线正在运行中 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_schedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 调度配置列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_ScheduleResponse"];
                };
            };
        };
    };
    create_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreateRequest"];
            };
        };
        responses: {
            /** @description 调度配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ScheduleResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_trigger_logs: {
        parameters: {
            query?: {
                /** @description 按流水线过滤 */
                pipeline_id?: number;
                /** @description 页码 */
                page?: number;
                /** @description 每页条数 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 触发审计分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResponse_TriggerLogResponse"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务类型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    task_schema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务类型标识 */
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务输入 Schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
